### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by Ricks-Lab** [csecht/CountBOINCtasks#1]
Just had a few minutes for a quick look:

- Logger - Format should be "lazy" instead of "f" strings.  This way the message is only constructed if needed.  The python linter `pylint3` will also point this out. 
- Repository - You should add the .idea directory to your `.gitignore`.  Not sure, but there may be some private info in your `.idea` folder.
- venv - I would not upload venv details and instead include a recipe for how the user/developer can create the same venv as you.  
- Dictionaries - Quickly get comfortable with dictionaries and look for ways to include in your code.
- Class variables - In the BoincCommand class, constants should be defined as class variables before the `__init__` declaration.  This way, if multiple instances are created, the constants won't be repeated in each.

**Comment by csecht** [comment]
Good suggestions, thanks.

- Logger f-string format changed to lazy.
- Select `.idea` files added to `.gitignore` per https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore
- venv folder deleted from repository.
- Working on using more dictionaries.
- Moved class constants out of __init__
- pylint is keeping me busy with additional code polishing.
