### ISSUE TITLE
Program does not run with non-default BOINC directory location

### ISSUE THREAD

**Issue by KeithMyers** [csecht/CountBOINCtasks#4]
Just gave the program a try on Ubuntu 20.04.1 LTS.
keith@Serenity:~/Downloads/CountBOINCtasks-master$ ./count-tasks.py
Bad path for boinccmd: /usr/bin/boinccmdkeith@Serenity:~/Downloads/CountBOINCtasks-master$

Probably needs a new parameter specifying where to find boinccmd.

**Comment by csecht** [comment]
Thanks for testing.  Yes, I am aware of the non-default path problem, but haven't yet figured out a general approach for how to set a custom path to boinccmd. Much to learn!

**Comment by KeithMyers** [comment]
Something like a config file?  Pose the question to Rick at Ricks-Lab.  He uses a Bench.cfg file and I have this in it.
#Specify path for BOINC
mode boinc_home /home/keith/Desktop/BOINC/

**Comment by csecht** [comment]
The latest commit can handle non-default BOINC paths on Windows and Linux. As a temporary fix, is a command line option to enter a custom path. Hope to have a CFG file option in time. 
Let me know if this work in Windows; there may be some Windows path formats I haven't taken into account. It should work with /Users/keith/Desktop/BOINC/boinccmd.exe; not sure about /home/keith/....  (My knowledge of Windows command line usage is weak.)
Mac OS execution still only accepts the default BOINC path.

**Comment by KeithMyers** [comment]
No, your prompt for inputting my BOINC folder location did not work.
keith@Serenity:~/Downloads/CountBOINCtasks-master$ ./count-tasks.py

boinccmd is not in its default path: /usr/bin/boinccmd
Enter your custom path to execute boinccmd: /home/keith/Desktop/BOINC
Oops. /home/keith/Desktop/BOINC is a bad path.
Try again. Exiting now...

**Comment by csecht** [comment]
The path needs to include the executable. Try:  /home/keith/Desktop/BOINC/boinccmd
I’ll can see I need to clarify that message.

**Comment by KeithMyers** [comment]
Oh.  I just did a pwd and copy and pasted from the terminal I opened in the BOINC folder.
Will give the new location a try.

**Comment by KeithMyers** [comment]
Works if you append the name of the boinccmd executable to the path.
