### ISSUE TITLE
Getting error on argument "capture_output"

### ISSUE THREAD

**Issue by JStateson** [csecht/CountBOINCtasks#5]
Using python 3.6.9 program is generating error on ubuntu 18.04.  I only dabble in python so not sure what is going on but i did find other reports of same problem

'jstateson@h110btc: /Projects/CountBOINCtasks-master$ python3 -V
Python 3.6.9
...
jstateson@h110btc:~/Projects/CountBOINCtasks-master$ ./count-tasks.py
TypeError: __init__() got an unexpected keyword argument capture_output'

I googled the above error and found a discussion [https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output/53209196](url)  so it is a known problem

**Comment by csecht** [comment]
Thanks much for that link. I thought I had vetted it on Python 3.6, but obviously missed that one; the `capture_output` keyword was not introduced until Python 3.7.
It should work now with your version of Python. Download the latest commit and give it a try.
