### ISSUE TITLE
Custom boinccmd path is not sticky

### ISSUE THREAD

**Issue by KeithMyers** [csecht/CountBOINCtasks#6]
I closed the previous issue too soon it seems.  I used the default settings for count-tasks and left the terminal running.
I just had the first 60 minute countdown and I expected to see the next updated stats.
However the program just threw the original complaint about not finding the executable in the standard path.
The program needs to remember where the custom path is and be persistent.
keith@Serenity:~/Downloads/CountBOINCtasks-master$ ./count-tasks.py

boinccmd is not in its default path: /usr/bin/boinccmd
Enter your custom path to execute boinccmd: /home/keith/Desktop/BOINC/boinccmd
2020-Nov-04 15:44:10; Tasks reported in the past hour: 88
                      Task Times: mean 00:16:25, range [00:01:55 - 00:52:08],
                                                 stdev 00:11:03, total 1d 00:05:41
1m |< ~time to next count
boinccmd is not in its default path: /usr/bin/boinccmd
Enter your custom path to execute boinccmd:

**Comment by csecht** [comment]
I completely missed that bug. I will work on a fix tomorrow.

**Comment by csecht** [comment]
The latest commit (beta version 0.4.4) should now allow custom paths to stick. See if you can confirm.

**Comment by csecht** [comment]
The latest commit (v.0.4.5) has the option to set the boinccmd path in a configuration file.

**Comment by KeithMyers** [comment]
+1 for the addition of the config.txt file for the custom boinccmd path.
Works very well now. Closing issue as fixed.
